[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "APCS文檔"
authors = [{name = "Chinococo", email = "garyliuyahoocom384@gmail.com"}]
dynamic = ["version", "description"]
